os:
  osx
language: 
  swift
osx_image: 
  xcode11.2
script:
  - sw_vers
  - swift build
  - swift test --enable-code-coverage
after_success:
  - xcrun llvm-cov report .build/debug/SwiftLoggerPackageTests.xctest/Contents/MacOS/SwiftLoggerPackageTests -instr-profile .build/debug/codecov/default.profdata
  - xcrun llvm-cov export -format="lcov" .build/debug/SwiftLoggerPackageTests.xctest/Contents/MacOS/SwiftLoggerPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
  - bash <(curl https://codecov.io/bash)
